# Generated by Django 2.0 on 2018-07-14 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('rue', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('departement', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Antecedant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CentreAmbulancier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_malade', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('motif_reference', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Clinique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(max_length=255)),
                ('horaire', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dispensaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_generale', models.CharField(max_length=255)),
                ('horaire_personnel', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostique', models.TextField()),
                ('id_antecedant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santec.Antecedant')),
            ],
        ),
        migrations.CreateModel(
            name='ElementsousCategorie_ante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_element', models.CharField(max_length=255, verbose_name='Valeur Sous Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Hopitaux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalisation', models.CharField(max_length=255)),
                ('consultation', models.CharField(max_length=255)),
                ('intervention', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('sexe', models.CharField(max_length=2, verbose_name='Sexe')),
                ('religion', models.CharField(max_length=255, verbose_name='Religion')),
                ('personne_respon', models.CharField(max_length=255, verbose_name='Nom Personne Resposable')),
                ('profession', models.CharField(max_length=255, verbose_name='Profession')),
                ('groupe_sanguin', models.CharField(max_length=1, verbose_name='Groupe Sanguin')),
                ('allergie_connu', models.CharField(max_length=255, verbose_name='Allergie Connu')),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la personne')),
                ('prenom', models.CharField(max_length=255, verbose_name='Prenom de la personne')),
                ('telephone', models.CharField(max_length=255, verbose_name='Telephone')),
                ('id_adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santec.Adresse')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelMedical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialiste', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santec.Personne')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_medicament', models.CharField(max_length=255)),
                ('type_medicament', models.CharField(max_length=255)),
                ('categorie_med', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=255, verbose_name='Nom Service')),
                ('description_service', models.TextField()),
                ('type_service', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sous_type_antecedant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_sous_type', models.CharField(max_length=255, verbose_name='Noms Sous Type')),
                ('id_ElementsousCategorie_ante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santec.ElementsousCategorie_ante')),
            ],
        ),
        migrations.CreateModel(
            name='Type_antecedant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type_antecedant', models.CharField(max_length=255, verbose_name='Nom Type Antecedant')),
                ('id_sous_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santec.Sous_type_antecedant')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='id_personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santec.Personne'),
        ),
        migrations.AddField(
            model_name='hopitaux',
            name='id_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santec.Service'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='id_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santec.Patient'),
        ),
        migrations.AddField(
            model_name='antecedant',
            name='id_type_antecedant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santec.Type_antecedant'),
        ),
    ]
